### ISSUE TITLE
Frontend Filters Improvements

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-blocks#10566]
```[tasklist]
### Make the filters contextual (relative to the products shown in the product grid keeping in mind of pagination) but keep the solution performant for large stores.
- [ ] Add a draft title or issue reference here
```

```[tasklist]
### Potentially optimize filters to avoid any re-rendering.
- [ ] Add a draft title or issue reference here
```

```[tasklist]
### Explore how the Interactivity API can be utilized for any related improvements.
- [ ] Add a draft title or issue reference here
```

**Comment by dinhtungdu** [comment]
## Phase 1 - Cycle 5 - August 14th – October 6th

The goal of this project is to improve the performance of all filters that effects the products blocks. We need to take in account for large stores with many products.

```[tasklist]
### Make the filters contextual (relative to the products shown in the product grid) but keep the solution performant for large stores.
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10985
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10569
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10570
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10572
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10573
```

```[tasklist]
### Potentially optimize filters to avoid any re-rendering.
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10577
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10578
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10579
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10580
```

```[tasklist]
### Explore how the Interactivity API can be utilized for any related improvements.
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10814
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10813
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10811
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10812
```


```[tasklist]
### Convert/Add e2e tests to Playwright
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10588
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10589
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10590
```

```[tasklist]
### Create new collection filters block
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10711
- [ ] https://github.com/woocommerce/woocommerce-blocks/issues/10984
```

**Comment by Marc-pi** [comment]
@dinhtungdu / @roykho i found finaly the EPIC issue about filters :-)
One question : what's your performance target in term of max nr of product ?
do you plan to manage indexes to speed up things, or other improvements to well manage the larger shops (here i'm running 80-100K products with Woo).

**Comment by dinhtungdu** [comment]
@Marc-pi We haven't look at the performance yet so I can't give you any insights/information on that matter right now. I will raise this to our team to discuss.

Personally, for the size of the store you're running, I will use specialized solution like Elasticsearch to improve the performance.

**Comment by Marc-pi** [comment]
@dinhtungdu for now we make use of wpgridbuilder, and it's mostly 80-100K hidden behing grouped products (approx 25K grouped products), for which we've build our own templates / plugin to manage the missing features. 
(as you know, the grouped product FSE template is not available yet into WCBlocks, it uses the single product template only where there are encapsulated templates to manage the display of child product element). 
keep it up, i see you're moving quite fast on those new filters with interactive API.
glad to see. 
NB : when released, would be nice to indicate the perf target so people will be aware of
