### ISSUE TITLE
Product Collection - replace All Products with Collections

### ISSUE THREAD

**Issue by kmanijak** [woocommerce/woocommerce-blocks#11369]
### Background

With the Collections, they can start replacing other blocks based on All Product block.

### Requirements

1. "Old" blocks are hidden from inserter so
2. "New" collections are enabled in the inserter and each collection includes the keyword referencing to "old" block allowing for easy discovery.
3. Replace the blocks in the patterns or other blocks that may use it.
4. "Old" blocks ARE NOT removed from the codebase! They have to be preserved so they work in existing stores that rely on them!

```[tasklist]
### Tasks
- [ ] Best Selling Products -> Top Sellers collection
- [ ] Top Rated Products -> Top Rated Products collection
- [ ]  Newest Products -> New Arrivals collection
- [ ]  On Sale Products -> On Sale Products collection
- [ ]  Hand-picked Products -> Hand-picked Products collection
- [ ]  ??? -> Featured Products collection
- [ ]  Upsells -> Upsells collection
- [ ]  Cross-Sells -> Cross-Sells collection
```
